### ISSUE TITLE
"msg": "Unexpected failure during module execution: too many values to unpack (expected 2)"

### ISSUE THREAD

**Issue by ivanmpk** [ansible-collections/community.routeros#176]
##### SUMMARY

I can not use routeros module with my current config, I'm getting an unexpected failure.
I can connect via SSH from my Ubuntu to RouterOS.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ivan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ivan/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ivan/.local/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
community.routeros 2.8.0 
```

##### CONFIGURATION

```paste below
[defaults]
inventory=/etc/ansible/hosts
deprecation_warnings=False

[inventory]
enable_plugins = yaml, ini

```

##### OS / ENVIRONMENT

Ubuntu 22.04.2 LTS
RouterOS 7.10rc1 and also on 6.48.7

##### STEPS TO REPRODUCE

ansible-playbook -vvvv routeros-playbook.yml --inventory /etc/ansible/hosts --extra-vars "ansible_user=admin ansible_network_os=routeros ansible_become=yes ansible_become_method=enable"

```yaml
---

- hosts: mikrotiks
  connection: network_cli
  gather_facts: false

  tasks:

    - name: Display resource statistics (routeros)
      routeros_command:
        commands: 
          - /system resource print
      register: routeros_resources


```

##### ACTUAL RESULTS

```paste below
ansible-playbook [core 2.14.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ivan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ivan/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ivan/.local/bin/ansible-playbook
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
[WARNING]:  * Failed to parse /etc/ansible/hosts with yaml plugin: We were unable to read either as JSON nor YAML, these are the errors we got from each: JSON: Expecting value: line 1 column 2 (char 1)  Syntax
Error while loading YAML.   did not find expected <document start>  The error appears to be in '/etc/ansible/hosts': line 2, column 1, but may be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:  [mikrotiks] server1 ansible_host=127.0.0.1 ^ here
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/yaml.py", line 107, in parse
    raise AnsibleParserError(e)
[WARNING]:  * Failed to parse /etc/ansible/hosts with ini plugin: /etc/ansible/hosts:4: Section [mikrotiks:var] has unknown type: var
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/ini.py", line 137, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse /etc/ansible/hosts as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
redirecting (type: modules) ansible.builtin.routeros_command to community.routeros.command
Loading collection community.routeros from /home/ivan/.ansible/collections/ansible_collections/community/routeros
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python3/dist-packages/ansible/plugins/callback/default.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: routeros-playbook.yml ***********************************************************************************************************************************************************************************
Positional arguments: routeros-playbook.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/etc/ansible/hosts',)
extra_vars: ('ansible_user=admin ansible_network_os=routeros',)
forks: 5
1 plays in routeros-playbook.yml

PLAY [mikrotiks] **************************************************************************************************************************************************************************************************

TASK [Display resource statistics (routeros)] *********************************************************************************************************************************************************************
task path: /home/ivan/routeros-playbook.yml:9
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
Loading collection ansible.netcommon from /home/ivan/.ansible/collections/ansible_collections/ansible/netcommon
Loading collection ansible.utils from /home/ivan/.ansible/collections/ansible_collections/ansible/utils
redirecting (type: terminal) ansible.builtin.routeros to community.routeros.routeros
redirecting (type: cliconf) ansible.builtin.routeros to community.routeros.routeros
<127.0.0.1> attempting to start connection
<127.0.0.1> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /home/ivan/.local/bin/ansible-connection
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/usr/lib/python3/dist-packages/ansible/executor/task_executor.py", line 580, in _execute
    socket_path = start_connection(self._play_context, options, self._task._uuid)
  File "/usr/lib/python3/dist-packages/ansible/executor/task_executor.py", line 1221, in start_connection
    for level, message in result['messages']:
ValueError: too many values to unpack (expected 2)
fatal: [server1]: FAILED! => {
    "msg": "Unexpected failure during module execution: too many values to unpack (expected 2)",
    "stdout": ""
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
server1                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
  


```

**Comment by felixfontein** [comment]
I'm not sure where this error comes from, the code in this collection does not output `messages`.

Are you sure you are actually using the `command` module from this collection? After all you are using the `community.network.routeros_command` module, not `community.routeros.command`. Depending on the version of `community.network` the former is a redirect to the later - or not.

Another thing: does this also happen with `ansible_become=false`?

**Comment by ivanmpk** [comment]
Hi @felixfontein thank you for quick answer, I tried with ansible_become=false and get the same error. I updated my comment when I tried with `routeros.command`.

**Comment by felixfontein** [comment]
In that case I'm out of ideas (that don't involve modifying code to get ideas what goes wrong). You could try to figure out what goes wrong, by adding a `print(result)` before line 1221 of /usr/lib/python3/dist-packages/ansible/executor/task_executor.py.

**Comment by ivanmpk** [comment]
Thanks again @felixfontein, it seems like ansible can't connect via SSH, I don't understand why because I can connect through SSH without ansible from same environment & credentials.

```
{'error': "paramiko: The authenticity of host '192.168.56.103' can't be established.\nThe ssh-rsa key fingerprint is b'e1e1386b687b7421fc4cc6522ba9098c'.", 'exception': 'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/ansible/plugins/connection/paramiko_ssh.py", line 428, in _connect_uncached\n    ssh.connect(\n  File "/home/ivan/.local/lib/python3.10/site-packages/paramiko/client.py", line 460, in connect\n    self._policy.missing_host_key(\n  File "/usr/lib/python3/dist-packages/ansible/plugins/connection/paramiko_ssh.py", line 263, in missing_host_key\n    raise AnsibleError(AUTHENTICITY_MSG[1:92] % (hostname, ktype, fingerprint))\nansible.errors.AnsibleError: paramiko: The authenticity of host \'192.168.56.103\' can\'t be established.\nThe ssh-rsa key fingerprint is b\'e1e1386b687b7421fc4cc6522ba9098c\'.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/ivan/.local/bin/ansible-connection", line 106, in start\n    self.connection._connect()\n  File "/home/ivan/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/network_cli.py", line 639, in _connect\n    ssh = self.ssh_type_conn._connect()\n  File "/usr/lib/python3/dist-packages/ansible/plugins/connection/paramiko_ssh.py", line 310, in _connect\n    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()\n  File "/usr/lib/python3/dist-packages/ansible/plugins/connection/paramiko_ssh.py", line 454, in _connect_uncached\n    raise AnsibleConnectionFailure(msg)\nansible.errors.AnsibleConnectionFailure: paramiko: The authenticity of host \'192.168.56.103\' can\'t be established.\nThe ssh-rsa key fingerprint is b\'e1e1386b687b7421fc4cc6522ba9098c\'.\n', 'messages': ['local domain socket does not exist, starting it', 'control socket path is /home/ivan/.ansible/pc/cd2edfb071', ''], 'socket_path': '/home/ivan/.ansible/pc/cd2edfb071'}
```

**Comment by ivanmpk** [comment]
Ok I added `host_key_checking = False` in my ansible.cfg file and now the result of print(result) is the following:

```
{'messages': ['local domain socket does not exist, starting it', 'control socket path is /home/ivan/.ansible/pc/cd2edfb071', 'connection to remote device started successfully', 'local domain socket listeners started successfully', ''], 'socket_path': '/home/ivan/.ansible/pc/cd2edfb071'}
```

**Comment by ivanmpk** [comment]
Ok I solved it, it was related to permission on local directory and also I added `[paramiko_connection]
look_for_keys=False
` in my ansible.cfg

**Comment by felixfontein** [comment]
Thanks for debugging this! These messages are printed by ansible-connection, but from the code it looks like it should not return what you are printing. I tried reproducing this, but for me ansible-connection always prints the messages in the expected format. :shrug:

**Comment by felixfontein** [comment]
This is a bit similar to https://github.com/ansible/ansible/issues/61811. CC @Qalthos who looked at it back then, maybe she has an idea what could be happening here...

**Comment by felixfontein** [comment]
@sivel pointed out on IRC that ansible-connection was changed for Ansible 2.8.0 (https://github.com/ansible/ansible/commit/1829a72885de1b6dd46799d9b87e8cd6210a8038), older versions are emitting `messages` in the format you are showing. So a likely cause for this problem is that you have an `ansible-connection` executable from an Ansible version < 2.8.0 lying around in your `$PATH` (`/home/ivan/.local/bin/ansible-connection` according to the logs), and that ansible-core 2.14.6 (installed in `/usr/lib/python3/dist-packages/ansible/`) is using that executable instead of the one that belongs to itself.

Removing that ansible-connection executable should probably fix the problem.
